version: 2

references:

  container_config: &container_config
    docker:
      - image: circleci/node:4.8.3
    environment:
      - NPM_VERSION: 5.4.2

  repository_cache_key: &repository_cache_key
    v1-repository-{{ .Branch }}-{{ .Revision }}

  restore_repository: &restore_repository
    restore_cache:
      keys:
        - *repository_cache_key

  cache_repo: &cache_repo
    save_cache:
      key: v1-repository-{{ .Branch }}-{{ .Revision }}
      paths:
        - .

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

  update_npm: &update_npm
    run:
      name: Update npm
      command: sudo npm install -g npm@$NPM_VERSION

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repository
      - checkout
      - *cache_repo

  install_dependencies:
    <<: *container_config
    steps:
      - *restore_repository
      - *restore_node_modules

      - *update_npm
      - run:
          name: Install dependencies
          command: npm install

      - *cache_node_modules

  test:
    <<: *container_config
    steps:
      - *restore_repository
      - *restore_node_modules

      - run:
          name: Run Tests
          command: npm test

  release:
    <<: *container_config
    steps:
      - *restore_repository
      - *restore_node_modules

      - *update_npm

      - run:
          name: Prune devDependencies
          command: npm prune --production

      - deploy:
          command: |
            npm install -g npm-cli-login
            NPM_USER=$NPM_USER NPM_PASS=$NPM_PASSWORD NPM_EMAIL=$NPM_EMAIL npm-cli-login
            npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - release:
          requires:
            - test
          branches:
            ignore: /.*/
          filters:
            tags:
              only: /v.*/

experimental:
  notify:
    branches:
      only:
        - master
