version: 2.1

orbs:
  ft-snyk-orb: financial-times/ft-snyk-orb@0

references:

  container_config: &container_config
    working_directory: ~/project/eslint-config
    docker:
      - image: circleci/node:8.10

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

  only_version_tags: &only_version_tags
    tags:
      only: /^v[0-9]+$/

jobs:
  install:
    <<: *container_config
    steps:
      - checkout
      - *restore_node_modules

      - run:
          name: Install dependencies
          command: npm install

      - *cache_node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - eslint-config

  test:
    <<: *container_config
    steps:
      - *attach_workspace

      - run:
          name: Run Tests
          command: npm run lint:ci && npm test

  release:
    <<: *container_config
    steps:
      - *attach_workspace

      - run:
          name: Prune devDependencies
          command: npm prune --production

      - deploy:
          command: |
            NPM_USER=$NPM_USER NPM_PASS=$NPM_PASSWORD NPM_EMAIL=$NPM_EMAIL npx npm-cli-login
            npm version --no-git-tag-version $CIRCLE_TAG
            npm publish --access public

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
#Scan package.json for vulnerable dependencies while developing
      - ft-snyk-orb/scan-js-packages:
          context: rel-eng-creds
          requires:
          - install
          filters: *only_version_tags
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
#Scan and monitor vulnerabilities once in production
      - ft-snyk-orb/scan-and-monitor-js-packages:
          name: snyk-scan-and-monitor
          context: rel-eng-creds
          requires:
            - release
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/


experimental:
  notify:
    branches:
      only:
        - master
