version: 2

references:

  container_config: &container_config
    docker:
      - image: circleci/node:4.8.3
    environment:
      - NPM_VERSION: 5.4.2

  repository_cache_key: &repository_cache_key
    v1-repository-{{ .Branch }}-{{ .Revision }}-{{ .Environment.NPM_VERSION }}

  restore_repository: &restore_repository
    restore_cache:
      keys:
        - *repository_cache_key

  cache_repo: &cache_repo
    save_cache:
      key: v1-repository-{{ .Branch }}-{{ .Revision }}-{{ .Environment.NPM_VERSION }}
      paths:
        - .

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "package-lock.json" }}-{{ .Environment.NPM_VERSION }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

  cache_node_modules: &cache_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repository
      - checkout
      - *cache_repo

  install_dependencies:
    <<: *container_config
    steps:
      - *restore_repository
      - *restore_node_modules

      - run:
        name: Update npm
        command: sudo npm install -g npm@$NPM_VERSION

      - *cache_node_modules
      - *cache_repo

  test:
    <<: *container_config
    steps:
      - *restore_repository

      - run:
        name: Run tests
        command: npm test

  release:
    <<: *container_config
    steps:
      - *restore_repository

      - run:
        name: Prune devDependencies
        command: npm prune --production

      - deploy:
          command: |
            echo "_auth = $NPM_AUTH" >> .npmrc
            echo "email = $NPM_EMAIL" >> .npmrc
            npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v.*/
