version: 2

jobs:
  checkout_code:
    working_directory: ~/eslint-config-de-tooling
    docker:
      - image: circleci/node:4.8.3
    steps:
      - checkout

      - save_cache:
          key: v1-repository-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/eslint-config-de-tooling

  install_dependencies:
    environment:
      - NPM_VERSION: 5.4.2
    working_directory: ~/eslint-config-de-tooling
    docker:
      - image: circleci/node:4.8.3

    steps:
      - restore_cache:
        keys:
          - v1-repository-{{ .Environment.CIRCLE_SHA1 }}

      - run:
        name: Update npm
        command: sudo npm install -g npm@$NPM_VERSION

      - restore_cache:
        key: v1-dependencies-{{ .Environment.NPM_VERSION }}-{{ checksum "package-lock.json" }}

      - run:
        name: Install dependencies
        command: npm install

      - save_cache:
          key: v1-dependencies-{{ .Environment.NPM_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    environment:
      - NPM_VERSION: 5.4.2
    working_directory: ~/eslint-config-de-tooling
    docker:
      - image: circleci/node:4.8.3
    steps:
      - restore_cache:
        keys:
          - v1-repository-{{ .Environment.CIRCLE_SHA1 }}
          - v1-dependencies-{{ .Environment.NPM_VERSION }}-{{ checksum "package-lock.json" }}

      - run:
        name: Run tests
        command: npm test

      - run:
        name: Prune devDependencies
        command: npm prune --production

  release:
    environment:
      - NPM_VERSION: 5.4.2
    working_directory: ~/eslint-config-de-tooling
    docker:
      - image: circleci/node:4.8.3
    steps:
      - restore_cache:
        keys:
          - v1-repository-{{ .Environment.CIRCLE_SHA1 }}
          - v1-dependencies-{{ .Environment.NPM_VERSION }}-{{ checksum "package-lock.json" }}

      - deploy:
          command: |
            echo "_auth = $NPM_AUTH" >> .npmrc
            echo "email = $NPM_EMAIL" >> .npmrc
            npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v.*/
